### PR TITLE
Ignore Automake config files

### PR DESCRIPTION
**Pull request by cicku**
These files need to be updated by autoreconf for every new release, we shouldn't ship these files in vcs repo.

### CODE REVIEW

**Comment by joewing** [comment]
I agree, thanks!

**Comment by Israel-** [comment]
Hey @joewing after this commit I have had issues building it into a Ubuntu package for my PPA.
When I try to build the package I get exit status 127 (i.e. cannot find the executable I am trying to run)
manually running ./configure returns with this error.
`configure: error: cannot run /bin/bash ./config.sub`
I know you removed these since they are supposed(?) to be auto generated by autoconf.
I did not find any helpful option to create the sub file in ./configure --help 

I build the debian package using:
`dh $@ --with autotools_dev`
a specific debian-helper command to run the reconfiguration of an autotools project.
This may end up being something really simple, but as for now I need to be pointed to the right direction.
Thanks

**Comment by cicku** [comment]
These config files shouldn't be included in git, because they are just junks for building only, and can be regenerated at anytime by anyone.

You can rebuild these by running `autoreconf -fiv`. I'm not sure why you don't even know this.

**Comment by cicku** [comment]
These config files shouldn't be included in git, because they are just junks for building only, and can be regenerated at anytime by anyone.

You can rebuild these by running `autoreconf -fiv`. I'm not sure why you don't even know this.

**Comment by Israel-** [comment]
Thanks for your help, you were very direct.

To answer your question:
 I didn't know this because I am not as accomplished as you are.  I have not gone to school for this, nor do I do this for a living, and conceivably you are more brilliant than I.
I am an enthusiastic user who wants more people to have an up-to-date version of JWM in Ubuntu.  Debian does not maintain this program's package the official version in my repo is `2.1.0+svn579-2ubuntu1`  which also is not compiled with SVG support, neither does it have JPEG support.  This is unacceptable to someone who wants a modern, beautiful desktop that does not hog resources.

Again, thanks for your direct answer

**Comment by technosaurus** [comment]
@Israel- don't consider yourself unaccomplished for lack of understanding of autofools (intentionally misspelled)  The more people learn it, the more they want to use something else (kernel, busybox, toybox, agar, many bsd projects).  I get a much better build using a single gcc command line anyhow.

...but as long as we are ignoring the files, it would make sense to add these files to the distclean make target, to enable cleaner patches (such as 200kb of superfluous ./configure changes)

**Comment by cicku** [comment]
@Israel- Sounds sarcastic to me, I'm always a noob, if you know how old I am. :joy:

There are only few people are master of autofools, that's why autofool name was given. :joy:

Meanwhile, I've compiled every supported feature for jwm in Fedora. (Ignore I'm an advocate of Fedora)

**Comment by Israel-** [comment]
@cicku I wasn't being sarcastic.  I looked at your github profile, you really do seem to be very accomplished, and I genuinely meant it.
I do like Fedora, and use it from time to time.
I do not know how old you are.  I use cmake for my projects, though I am not a master of that either.
@technosaurus a single gcc line is great, though you cannot install all the other things that come with a project, so we do need one of these systems to install everything else

**Pull request merged**
