### PR TITLE
Add Aero Snap

### PR DESCRIPTION
**Pull request by n-a-m-e**
Lots of other window managers like kde, gnome, xfce, windows 7 have the feature where when you drag a window to the edge of the screen it will maximise to half the screen size. It becomes a habit after a while to just drag to the edge and I was finding it really annoying that jwm didn't have this feature and I think other people would appreciate it aswell if you added it to jwm as a default behaviour.

### CODE REVIEW

**Comment by joewing** [comment]
Thanks for the PR!  There is an old issue for this (issue #49). 
This change doesn't entirely work for me; I'm only able to get maximization to work at the top of my screen.  I haven't really looked into why that is yet though.  It would also be nice if dragging to a side of a screen maximized, and then dragging away undid the maximization.  I don't think that should be difficult to make work (actually, I thought it would, so that could be some other issue).

**Comment by n-a-m-e** [comment]
Hey thanks for the response, I cleaned up the code so that it checks first if it the window is maximized and only maximizes if it isn't already maximised, and that it always restores the window to normal size when it is dragged away from the edge.

I've set it up so that the top and bottom maximize to full-screen, left and right maximize vertically and the corners maximize horizontally. Iv'e attached a gif bellow to show an example.

Let me know if you still have any problems with it :-)

Also it would be nice if we could also maximize to a quarter of the screen instead of just half but I think for the time being this works very nicely.

aero-snap

**Comment by n-a-m-e** [comment]
Well I spent some more time on it and I'm pretty sure it's perfect now :-) Thanks for making such an awesome hackable window manager.

Fullscreen = drag to (top OR bottom) edge
Left Half = drag to left edge
Right Half = drag to right edge
Top Half = drag to top edge then drag to (left OR right) edge
Bottom Half = drag to bottom edge then drag to (left OR right) edge
Top Left Corner = drag to left edge then drag to top edge
Top Right Corner = drag to right edge then drag to top edge
Bottom Left Corner = drag to left edge then drag to bottom edge
Bottom Right Corner = drag to right edge then drag to bottom edge

aero-snap-better

**Comment by STrRedWolf** [comment]
Can you make sure this is an optional (ie can be disabled)?  I'm in the "GAWD That is ANNOYING kill that crap" camp when it comes with Aero Snap.  For example, I have a (terminal) window the way I want it and I want to move it to the corner, having it expand in weird ways makes me say "WTF?!? I wanted it snapped against the side, NOT RESIZED!!!"

Yes, I'm old school.  I grew up on FVWM.

**Comment by n-a-m-e** [comment]
Hey STrRedWolf, Thanks for the input. This will not actually interfere with the normal window snapping at all, and in the scenario you describe you would not notice it at all, The window maximising only occurs once the mouse cursor is touching the edge of the screen. 
Also if you drag the window away again it regains whatever shape it had before it was maximised.
I've attached another gif to hopefully make this clearer.
Please let me know if this answers your concern or if you have any further questions.

example

**Comment by STrRedWolf** [comment]
That's the thing, is that I'm not that careful when I drag windows up to the edges and corner.  I **will** be forcing the drag up, so it's very possible to me to touch the top of the screen when I drag a window up -- which then gets the undesirable action.

Yes, I'm a brute in this regard.

**Comment by joewing** [comment]
I like to avoid configurable things where possible since it just leads to configurations that I don't test, but I could see this as being something that one might want for some windows and not others.  So adding a group option for this might be the solution, something like:
```xml
<Group>
  <Option>aerosnap</Option>
</Group>
```
I guess the question is whether it should be enabled or disabled by default (the option inverted as necessary).

**Comment by STrRedWolf** [comment]
I'm for the option. I don't mind what the default is, as long as the option is there and I can change it.

**Comment by n-a-m-e** [comment]
Hey Guys.
I think that since all the other window managers have this on by default it's only logical to also have it on by default in JWM.

Also I tried my best to create a group option "noaerosnap" by copying how all the other group options looked, but whenever the program hits my if statement in move.c
<pre>
if(np->state.status & STAT_NOAEROSNAP) {
    aeroSnap = 0;
} else {
    aeroSnap = 1;
}
</pre>
it sets aeroSnap to 1 so i think STAT_NOAEROSNAP is always 0 regardless of wether the group option is set.

If someone could help implement the group option correctly I think this could then be merged into the master branch :-)

**Comment by joewing** [comment]
The parser uses a binary search to look for group options, so I think the only problem is that `noaerosnap` is not sorted lexicographically in the list of group options.

**Comment by n-a-m-e** [comment]
IT WORKS! thanks joewing.

I think if no-one else has any objections this is ready to be merged :-)

aero-snap-option

**Comment by Israel-** [comment]
sounds great to me, I like this as an available option!
To disable on all windows it will be much like disabling the shade function, right?
```
    <Group>
        <Option>noaerosnap</Option>
    </Group>
```
Or is this going to be disabled by default? and we need to enable it?
nice work!

**Comment by n-a-m-e** [comment]
Hey Israel-, Good to hear you like this feature aswell :-)
Aero Snap is on by default, and yes
```
<Group>
  <Option>noaerosnap</Option>
</Group>
```
does disable it for all windows.

**Comment by technosaurus** [comment]
I would prefer it to be set to off by default at least until the next major version change... just so users don't get "abnormal" behavior with their existing config files

**Comment by n-a-m-e** [comment]
Hi technosaurus, thanks for the input. I don't quite see the benefit of delaying this feature.

In my eye's if someone does not want this feature the amount of effort needed to edit their config file will be the same if it happens tomorrow or if it happens a couple of months from now, where as the people who will benefit from this feature will miss out on a couple of months of using it, since they probably won't know it exists.

So it seems to me that delaying this feature is detrimental to the people who would like to use it and has no real benefit to the people who are going to turn it off.

Please let me know if there is something else I'm missing.

**Comment by joewing** [comment]
I agree that this does change behavior, and maybe it should be saved for a larger bump in the version number.  On the other hand, that would mean either supporting both positive and negative forms of the option or breaking backwards compatibility at some point (if the default were to change).

In any case, I don't think that has to be decided immediately, so I'm planning on merging this for now.

**Comment by n-a-m-e** [comment]
Thanks joewing, it feels good contributing to an awesome project such as this :-)

**Comment by joewing** [comment]
To follow up on this, I decided that for JWM v2.3.6 this should be disabled by default since it is a change in behavior that users are likely to see.  So I changed the option to "aerosnap".  As a compromise, the example configuration enables the option.  I would feel better about breaking this if it were v2.4.0, but I would like to get some more fixes through before that and I'd like to make this available.

**Pull request merged**
