### PR TITLE
Kiosk option added

### PR DESCRIPTION
**Pull request by ciarez**
By group option in config, is possible to show a window maximized with close button only. When close button is pressed, jwm exit. This is good for web browser kiosk.

### CODE REVIEW

**Comment by joewing** [comment]
This is an interesting use case.  I certainly want JWM to be able to support things like this, but I don’t like adding options that would only be useful to such a limited audience.  It seems to me that the main thing that’s missing from JWM to support this without changes is the ability to have closing a window cause JWM to exit.  So I wonder if a more generic solution would be possible, for example, allowing custom window buttons which could be tied to actions much the way key bindings currently work.  That would allow you to add a button that was tied to “exec:jwm -exit”.  I think that’s ultimately the direction JWM should go, but it will take a while to get there.

**Comment by technosaurus** [comment]
You can basically already do this using notitle and making a fake title bar using a tray and maximized window with actions tied to tray buttons that look like normal title bar buttons

**Comment by ciarez** [comment]
Thanks to technosaurus for the good suggestion and I agree with joewing about a more generic solution. I made this change because some browsers have limited options and at that moment I found only this solution. Sorry if I can't help the project, I love JWM because is lightweight, powerful, simple to build and have a well written code.

**Comment by joewing** [comment]
I'm closing this for now.  Once issue #19 is implemented, adding the ability to add custom actions to window buttons would not be far off.

**Pull request closed without merging**
