### PR TITLE
Fix a error: no proper invocation of AM_INIT_AUTOMAKE was found

### PR DESCRIPTION
**Pull request by rdnvndr**

### CODE REVIEW

**Comment by joewing** [comment]
I'm not sure what the best way to fix that warning is (well, besides dumping autotools).  When I add the `AM_INIT_AUTOMAKE`, I get an error that there is no Makefile.am, which actually breaks the build rather than simply adding noise.

**Comment by rdnvndr** [comment]
I followed the recommendations:
https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation

**Comment by joewing** [comment]
They want you to use automake, but JWM doesn't really (and I certainly don't want to depend on more autotools!).  The only reason JWM invokes automake at all is to copy some of the scripts that configure depends on (maybe there's a way to get those without invoking automake?).  In any case when I add that, the autogen.sh script returns a non-zero exit code in addition to complaining that I'm not fully using all the autotools available to me.  The non-zero exit code causes the other scripts I use to package JWM to fail (I could make them ignore the status, but that seems unsavory).

I really need to get rid of this autotool mess at some point.

**Comment by Israel-** [comment]
@joewing are you thinking of using cmake instead?  Or did you have another idea?

**Comment by rdnvndr** [comment]
It is necessary to solve the problem:
```
$ ./autogen.sh
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
```

**Comment by joewing** [comment]
@Israel- cmake might be the solution (I've used it before and it seemed decent).  I do like the fairly standard setup that autotools provide, but in general it seems like they cause more problems than they solve.

@rdnvndr The problem is, that with this change autogen.sh returns an error status.  Without the change it complains, but it returns a successful status (and works despite the complaining).  Even with this change, it still complains about the missing Makefile.am.  So I won't merge this because it breaks my release process.

**Comment by rdnvndr** [comment]
@joewing Thank you for comments!

**Pull request closed without merging**
