### PR TITLE
po files: Comply with ISO 639-1

### PR DESCRIPTION
**Pull request by samueloph**
Hi, I'm currently working on becoming a new Debian Maintainer and the package I choose to focus on was jwm, the current status of the package in Debian is not very good, we're a lot of releases behind upstream and there were a few things to set up, I already did some cleaning on the old package and now I have a package for 2.3.4 almost ready for upload to Debian.

I found out that lintian (our package linter tool) reports that one of the po files is not complying with either ISO 639-1 nor ISO 639-2. Looking at the po files, it looks like the upstream goal is to comply with ISO 639-1, so I'm sending this patch that changes pt-br.po to pt_BR.po.

Pleas note that i'm sending this PR because I think this within the upstream interests and not Debian specific.

### CODE REVIEW

**Comment by Israel-** [comment]
@samueloph I spoke with Jari (the previous maintainer) on numerous occasion about updating JWM
If you would like I updated JWM's packaging so that it included Jpeg and SVG as well as having an updated rules file and I would be glad to help.  I also have a menu that is much better (and mostly xdg-compliant) than the Debian one which uses menu files rather than desktop files

**Comment by samueloph** [comment]
@Israel- when you say update JWM packaging, are you talking about the debian packaging? I already did some work there (like updated rules file), you can see it [here](https://mentors.debian.net/package/jwm), I totally appreciate your help, but currently I'm depending on a sponsor to make uploads (I've got one DD that's helping me) and I think it would be better to discuss this changes after I've got the first upload of 2.3.4 enter unstable (currently we have 2.1.0+svn579-3), is that ok to you?

**Comment by Israel-** [comment]
Here in my control I use this
```
autotools-dev,
 dh-autoreconf,
 debhelper (>= 9),
 libfribidi-dev (>= 0.19.2),
 libfontconfig1-dev,
 libcairo2-dev,
 librsvg2-dev,
 libjpeg62-turbo-dev | libjpeg62-dev,
 libpng-dev|libpng12-dev,
 libx11-6,
 libxext-dev,
 libxft-dev,
 libxinerama-dev,
 libxmu-dev,
 libxpm-dev,
 libxrender-dev,
 zlib1g-dev,
```
This works for both Debian Jessie and all versions of Ubuntu It adds jpeg and svg support
I am sure there is more to be done, as well.
But at least provide svg and jpeg support please!!

**Comment by samueloph** [comment]
@Israel- Are you the Ubuntu maintainer of the package?
I think we can discuss improvements to the package in our distros, If i recall correctly there are a few changes made by me that could be ported to Ubuntu too, can we talk in other place other than on this PR? I guess discussing this here is not a good practice.

I think jpeg and svg support are really nice and will add them asap (on the package that i'm working right now) if my sponsor agrees, and I think he will.

**Comment by joewing** [comment]
Thanks!

**Pull request merged**
