### PR TITLE
Fix a mouse binding for non english keymap

### PR DESCRIPTION
**Pull request by roandbox**

### CODE REVIEW

**Comment by roandbox** [comment]
IMHO it does not matter. For non english keymap "state" returns other value.   Therefore, the state must be converted to the ASCII  character.

**Comment by joewing** [comment]
What are the other things showing up in `state` that you're trying to mask out?  The point of `lockMask` here is to mask out things that we don't care about, so rather than pushing `0xFF` around, this should update `lockMask`, preferably using a constant from the X11 headers or updating the `lockMods` array.

**Comment by roandbox** [comment]
I'm wrong. Need further study of the problem

**Comment by roandbox** [comment]
I have not found a key symbol for state "0x200". I added masks. Constants for these bits don't exist in file "X.h"

**Comment by joewing** [comment]
I wonder if this is related to mouse buttons instead of the keyboard perhaps (do you have a mouse with more than 5 buttons)? It seems strange that the mask would be `1<<13`, which is right after `Button5Mask`.  In other words, it looks like this would be the logical place for `Button6Mask` and `1<<14` would be `Button7Mask`.

I think this is probably an ok fix, considering these values seem in line with what X11 defines for mouse masks and it doesn't appear to define anything higher than Button5.

In any case, would you mind squashing the first commit?
Thanks!

**Comment by roandbox** [comment]
I have a notebook LENOVO ThinkPad S540 without  mouse.  I think that bits 1<<13 and 1<<14 is number of  keymap in  Option "XkbLayout" us,ru".  I did not have time to check it out.

**Comment by roandbox** [comment]
> I think that bits 1<<13 and 1<<14 is number of keymap in Option "XkbLayout" us,ru"

That's right. A maximum of four working layouts.

**Comment by joewing** [comment]
Thanks!

**Pull request merged**
