### PR TITLE
This allows using lightweight image loaders, useful for small static builds.

### PR DESCRIPTION
**Pull request by technosaurus**
Fix for https://github.com/joewing/jwm/issues/242

This adds support for several image types and cuts RAM usage in half for svg images.

 The down side is that a small number of images that work with the full versions may not load, so disabled by default and overriden by the full version if selected

_nanosvg_
- svg

_stb_image_
- jpg
- png
- gif
- bmp
- tga
- psd
- pnm
- ppm
- pgm
- pic

I added these extensions to icon.c, but haven't updated configure.ac to disable them individually yet because we may not want to try _all_ of the extensions that are not listed in the xdg specifications.  I did however add some code to prevent trying adding extensions to paths that already have a known extension: this significantly reduce load time due to [N] less useless open() syscalls (causing user->kernel->user context switch)

### CODE REVIEW

**Comment by joewing** [comment]
I have no problem supporting this as external libraries (certainly useful for limited systems), but I would really rather not have local versions in the repo.  Having it in the local repo means that the version of the library and JWM are tied together.  Also, it puts the burden of maintenance on JWM.

The configure script should detect the presence of the library and use it if available or it could just be disabled by default.

**Comment by technosaurus** [comment]
I updated it to move the header files out of tree (there is no "library" per se).   The header files just need to be somewhere in the Include path now.

**Comment by dumblob** [comment]
It seems the patch needs a bit of love again as *master* already moved a bit further.

Anyway, I don't see any other reason why this patch could not be merged (I came across a system where a static build would be beneficial). What do you think @joewing?

**Comment by joewing** [comment]
I don’t mind doing the merge.  I’ve been meaning to play with this, I just have’t gotten around to it yet.  

One question about it that I have is, is it necessary to have a configure option for all the supported image types or should it either support this library or not?  I think one option is probably sufficient, but perhaps there is a reason for others.  I would prefer to keep the options down if possible.

**Comment by technosaurus** [comment]
I would prefere to leave the options as is since some users may specifically want to be able to use gif or bmp files (possibly some of the other formats) but others may want to use only png and disable jpeg.  I left out the SIMD configuration and a couple of other configurable things, but they could be automatically enabled if the system supports it.

 I set up the configuration message to only output which stb-image formats are configured when stb is enabled.  By default only png and jpeg are enabled when stb is enabled.

There is no standard location for stb-image.h AFAIK, but the overall project is stb, so it may be useful to add -I/usr/include/stb or put something about the repository in the docs https://github.com/nothings/stb

**Comment by technosaurus** [comment]
Should I redo this patch set in parts, splitting the nanosvg and stb_image support into separate patches?  If anyone is still interested that is.  Nanosvg is the biggest resource savings, since it eliminates dependency on rsvg, cairo, glib and their dependencies.

**Comment by Israel-** [comment]
@technosaurus 
I like nanosvg personally.  It is indeed light and works well for most SVG images.  I think it would be nice to eliminate extra dependencies for those that want it.

**Comment by wdlkmpx** [comment]
I'm interested in trying something like this, but i don't see any tarball with patched sources, this might actually fix some bugs by not using the big libs

**Comment by joewing** [comment]
So this is just not something I want to support, so I'm not going to merge it.

**Pull request closed without merging**
